version: '3'
services:
  api-service:
    build: ./api
    command: npm run dev
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: 9E_D2KJtq5sEn64BvznsPLAMKi2f6jZ
      DB_CONNECTION: pg
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: adonis
      PG_PASSWORD: adonis
      PG_DB_NAME: adonis
      MATT_PASSWORD: test123
      DO_SPACES_KEY: <DO_SPACES_KEY>
      DO_SPACES_SECRET: <DO_SPACES_SECRET>
      DO_SPACES_ENDPOINT: <DO_SPACES_ENDPOINT>
      DO_SPACES_NAME: <DO_SPACES_NAME>
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
  frontend-service:
    stdin_open: true
    build: ./frontend
    links:
      - api-service
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3331:3331
    depends_on:
      - db
      - api-service
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3331
      REACT_APP_API_HOST: 'http://localhost:3333'